import type {
  User,
  LeaveType,
  LeaveBalance,
  LeaveApplication,
  Regulation,
  DelegationMatrix,
} from '../types';

// ============================================================================
// Demo Users - All 6 Roles
// ============================================================================

export const DEMO_USERS: User[] = [
  // Employees
  {
    userId: 'emp001',
    employeeId: 'APTC-EMP-001',
    name: 'Ravi Kumar',
    email: 'ravi.kumar@aptransco.in',
    mobile: '+91 98765 43210',
    designation: 'Assistant Engineer',
    department: 'Operations',
    office: 'Visakhapatnam Circle',
    zone: 'Eastern Zone',
    headquarters: 'Visakhapatnam',
    gender: 'Male',
    dateOfJoining: '2018-06-15',
    dateOfBirth: '1990-03-20',
    role: 'Employee',
    controllingOfficer: 'co001',
    reportingOfficer: 'co001',
    sanctioningAuthority: 'sa001',
    isActive: true,
    createdAt: '2018-06-15T09:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },
  {
    userId: 'emp002',
    employeeId: 'APTC-EMP-002',
    name: 'Priya Sharma',
    email: 'priya.sharma@aptransco.in',
    mobile: '+91 98765 43211',
    designation: 'Junior Engineer',
    department: 'Maintenance',
    office: 'Vijayawada Circle',
    zone: 'Central Zone',
    headquarters: 'Vijayawada',
    gender: 'Female',
    dateOfJoining: '2020-01-10',
    dateOfBirth: '1992-07-15',
    role: 'Employee',
    controllingOfficer: 'co001',
    reportingOfficer: 'co001',
    sanctioningAuthority: 'sa001',
    isActive: true,
    createdAt: '2020-01-10T09:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },
  {
    userId: 'emp003',
    employeeId: 'APTC-EMP-003',
    name: 'Anil Reddy',
    email: 'anil.reddy@aptransco.in',
    mobile: '+91 98765 43212',
    designation: 'Senior Technical Assistant',
    department: 'Planning',
    office: 'Hyderabad HQ',
    zone: 'Head Office',
    headquarters: 'Hyderabad',
    gender: 'Male',
    dateOfJoining: '2015-03-25',
    dateOfBirth: '1988-11-30',
    role: 'Employee',
    controllingOfficer: 'co002',
    reportingOfficer: 'co002',
    sanctioningAuthority: 'sa002',
    isActive: true,
    createdAt: '2015-03-25T09:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },

  // Controlling Officers
  {
    userId: 'co001',
    employeeId: 'APTC-CO-001',
    name: 'Ramesh Babu',
    email: 'ramesh.babu@aptransco.in',
    mobile: '+91 98765 44001',
    designation: 'Executive Engineer',
    department: 'Operations',
    office: 'Visakhapatnam Circle',
    zone: 'Eastern Zone',
    headquarters: 'Visakhapatnam',
    gender: 'Male',
    dateOfJoining: '2010-04-01',
    dateOfBirth: '1980-05-15',
    role: 'ControllingOfficer',
    sanctioningAuthority: 'sa001',
    isActive: true,
    createdAt: '2010-04-01T09:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },
  {
    userId: 'co002',
    employeeId: 'APTC-CO-002',
    name: 'Lakshmi Devi',
    email: 'lakshmi.devi@aptransco.in',
    mobile: '+91 98765 44002',
    designation: 'Superintending Engineer',
    department: 'Planning',
    office: 'Hyderabad HQ',
    zone: 'Head Office',
    headquarters: 'Hyderabad',
    gender: 'Female',
    dateOfJoining: '2008-08-20',
    dateOfBirth: '1978-09-10',
    role: 'ControllingOfficer',
    sanctioningAuthority: 'sa002',
    isActive: true,
    createdAt: '2008-08-20T09:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },

  // HR/Assistant
  {
    userId: 'hr001',
    employeeId: 'APTC-HR-001',
    name: 'Suresh Reddy',
    email: 'suresh.reddy@aptransco.in',
    mobile: '+91 98765 45001',
    designation: 'Assistant Personnel Officer',
    department: 'Human Resources',
    office: 'Hyderabad HQ',
    zone: 'Head Office',
    headquarters: 'Hyderabad',
    gender: 'Male',
    dateOfJoining: '2012-06-10',
    dateOfBirth: '1985-12-05',
    role: 'HR',
    isActive: true,
    createdAt: '2012-06-10T09:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },
  {
    userId: 'hr002',
    employeeId: 'APTC-HR-002',
    name: 'Anitha Kumari',
    email: 'anitha.kumari@aptransco.in',
    mobile: '+91 98765 45002',
    designation: 'HR Officer',
    department: 'Human Resources',
    office: 'Vijayawada Circle',
    zone: 'Central Zone',
    headquarters: 'Vijayawada',
    gender: 'Female',
    dateOfJoining: '2014-02-15',
    dateOfBirth: '1987-06-22',
    role: 'HR',
    isActive: true,
    createdAt: '2014-02-15T09:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },

  // Sanction Authority
  {
    userId: 'sa001',
    employeeId: 'APTC-SA-001',
    name: 'V. Krishnamurthy',
    email: 'v.krishnamurthy@aptransco.in',
    mobile: '+91 98765 46001',
    designation: 'Chief Engineer',
    department: 'Operations',
    office: 'Hyderabad HQ',
    zone: 'Head Office',
    headquarters: 'Hyderabad',
    gender: 'Male',
    dateOfJoining: '2005-01-10',
    dateOfBirth: '1975-03-18',
    role: 'SanctionAuthority',
    isActive: true,
    createdAt: '2005-01-10T09:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },
  {
    userId: 'sa002',
    employeeId: 'APTC-SA-002',
    name: 'P. Venkateswara Rao',
    email: 'p.venkat@aptransco.in',
    mobile: '+91 98765 46002',
    designation: 'Personnel Officer',
    department: 'Human Resources',
    office: 'Hyderabad HQ',
    zone: 'Head Office',
    headquarters: 'Hyderabad',
    gender: 'Male',
    dateOfJoining: '2006-07-25',
    dateOfBirth: '1976-11-12',
    role: 'SanctionAuthority',
    isActive: true,
    createdAt: '2006-07-25T09:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },

  // Accounts
  {
    userId: 'acc001',
    employeeId: 'APTC-ACC-001',
    name: 'Madhavi Latha',
    email: 'madhavi.latha@aptransco.in',
    mobile: '+91 98765 47001',
    designation: 'Accounts Officer',
    department: 'Finance & Accounts',
    office: 'Hyderabad HQ',
    zone: 'Head Office',
    headquarters: 'Hyderabad',
    gender: 'Female',
    dateOfJoining: '2013-09-05',
    dateOfBirth: '1986-04-08',
    role: 'Accounts',
    isActive: true,
    createdAt: '2013-09-05T09:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },

  // Admin
  {
    userId: 'admin001',
    employeeId: 'APTC-ADMIN-001',
    name: 'System Administrator',
    email: 'admin@aptransco.in',
    mobile: '+91 98765 48001',
    designation: 'IT Administrator',
    department: 'Information Technology',
    office: 'Hyderabad HQ',
    zone: 'Head Office',
    headquarters: 'Hyderabad',
    gender: 'Male',
    dateOfJoining: '2010-01-01',
    dateOfBirth: '1982-01-01',
    role: 'Admin',
    isActive: true,
    createdAt: '2010-01-01T09:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },
];

// ============================================================================
// Leave Types Master Data
// ============================================================================

export const LEAVE_TYPES: LeaveType[] = [
  {
    leaveTypeId: 'lt001',
    name: 'Earned Leave',
    code: 'EL',
    description: 'Earned Leave with full pay and allowances',
    category: 'Standard',
    payType: 'FullPay',
    maxDaysPerSpell: 180,
    maxDaysPerYear: 365,
    maxSpellsPerYear: undefined,
    minDaysNotice: 15,
    requiredDocuments: [],
    medicalCertificateRequired: false,
    fitnessCertificateOnReturn: false,
    prefixSuffixAllowed: true,
    applicableRegulations: ['REG-01'],
    isActive: true,
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },
  {
    leaveTypeId: 'lt002',
    name: 'Half Pay Leave',
    code: 'HPL',
    description: 'Half Pay Leave on medical or personal grounds',
    category: 'Standard',
    payType: 'HalfPay',
    maxDaysPerSpell: 90,
    maxDaysPerYear: 180,
    minDaysNotice: 7,
    requiredDocuments: [],
    medicalCertificateRequired: false,
    fitnessCertificateOnReturn: false,
    prefixSuffixAllowed: true,
    applicableRegulations: ['REG-17'],
    isActive: true,
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },
  {
    leaveTypeId: 'lt003',
    name: 'Commuted Leave',
    code: 'CL',
    description: 'Half Pay Leave commuted to full pay',
    category: 'Standard',
    payType: 'FullPay',
    maxDaysPerSpell: 90,
    maxDaysPerYear: 90,
    minDaysNotice: 7,
    requiredDocuments: [],
    medicalCertificateRequired: false,
    fitnessCertificateOnReturn: false,
    prefixSuffixAllowed: true,
    applicableRegulations: ['REG-17'],
    isActive: true,
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },
  {
    leaveTypeId: 'lt004',
    name: 'Medical Leave (HPL on Medical Grounds)',
    code: 'HPL-MED',
    description: 'Half Pay Leave on medical grounds, commuted to full pay',
    category: 'Medical',
    payType: 'FullPay',
    maxDaysPerSpell: 180,
    maxDaysPerYear: 180,
    minDaysNotice: 0,
    requiredDocuments: ['Medical Certificate'],
    medicalCertificateRequired: true,
    fitnessCertificateOnReturn: true,
    prefixSuffixAllowed: false,
    applicableRegulations: ['REG-17'],
    isActive: true,
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },
  {
    leaveTypeId: 'lt005',
    name: 'Casual Leave',
    code: 'CAS',
    description: 'Casual Leave for short absences',
    category: 'Standard',
    payType: 'FullPay',
    maxDaysPerSpell: 5,
    maxDaysPerYear: 12,
    minDaysNotice: 0,
    requiredDocuments: [],
    medicalCertificateRequired: false,
    fitnessCertificateOnReturn: false,
    prefixSuffixAllowed: false,
    applicableRegulations: ['REG-08'],
    isActive: true,
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },
  {
    leaveTypeId: 'lt006',
    name: 'Special Casual Leave',
    code: 'SCL',
    description: 'Special Casual Leave for specific occasions',
    category: 'Special',
    payType: 'FullPay',
    maxDaysPerSpell: 15,
    maxDaysPerYear: 20,
    minDaysNotice: 0,
    requiredDocuments: [],
    medicalCertificateRequired: false,
    fitnessCertificateOnReturn: false,
    prefixSuffixAllowed: false,
    applicableRegulations: ['REG-09'],
    isActive: true,
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },
  {
    leaveTypeId: 'lt007',
    name: 'Maternity Leave',
    code: 'ML',
    description: 'Maternity Leave for female employees (26 weeks)',
    category: 'Maternity',
    payType: 'FullPay',
    genderRestriction: 'Female',
    maxDaysPerSpell: 182,
    maxDaysPerYear: 182,
    minDaysNotice: 30,
    requiredDocuments: ['Medical Certificate', 'Expected Date of Delivery'],
    medicalCertificateRequired: true,
    fitnessCertificateOnReturn: true,
    prefixSuffixAllowed: false,
    applicableRegulations: ['REG-18'],
    isActive: true,
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },
  {
    leaveTypeId: 'lt008',
    name: 'Paternity Leave',
    code: 'PL',
    description: 'Paternity Leave for male employees',
    category: 'Paternity',
    payType: 'FullPay',
    genderRestriction: 'Male',
    maxDaysPerSpell: 15,
    maxDaysPerYear: 15,
    minDaysNotice: 7,
    requiredDocuments: ['Birth Certificate'],
    medicalCertificateRequired: false,
    fitnessCertificateOnReturn: false,
    prefixSuffixAllowed: false,
    applicableRegulations: ['REG-19'],
    isActive: true,
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },
  {
    leaveTypeId: 'lt009',
    name: 'Child Care Leave',
    code: 'CCL',
    description: 'Child Care Leave for employees with children under 18',
    category: 'Special',
    payType: 'FullPay',
    maxDaysPerSpell: 730,
    maxDaysPerYear: 730,
    minDaysNotice: 15,
    requiredDocuments: ['Child Birth Certificate'],
    medicalCertificateRequired: false,
    fitnessCertificateOnReturn: false,
    prefixSuffixAllowed: false,
    applicableRegulations: ['REG-20'],
    isActive: true,
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },
  {
    leaveTypeId: 'lt010',
    name: 'Study Leave',
    code: 'SL',
    description: 'Study Leave for higher education',
    category: 'Special',
    payType: 'FullPay',
    maxDaysPerSpell: 730,
    maxDaysPerYear: 730,
    minServiceYears: 5,
    minDaysNotice: 60,
    requiredDocuments: ['Admission Letter', 'Course Details', 'Bond'],
    medicalCertificateRequired: false,
    fitnessCertificateOnReturn: false,
    prefixSuffixAllowed: false,
    applicableRegulations: ['REG-21'],
    isActive: true,
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },
  {
    leaveTypeId: 'lt011',
    name: 'Extraordinary Leave',
    code: 'EOL',
    description: 'Extraordinary Leave without pay',
    category: 'Standard',
    payType: 'NoPay',
    maxDaysPerSpell: 365,
    maxDaysPerYear: 730,
    minDaysNotice: 15,
    requiredDocuments: [],
    medicalCertificateRequired: false,
    fitnessCertificateOnReturn: false,
    prefixSuffixAllowed: false,
    applicableRegulations: ['REG-22'],
    isActive: true,
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },
  {
    leaveTypeId: 'lt012',
    name: 'Special Disability Leave',
    code: 'SDL',
    description: 'Special Leave for employees with disabilities',
    category: 'Special',
    payType: 'FullPay',
    maxDaysPerSpell: 60,
    maxDaysPerYear: 60,
    minDaysNotice: 7,
    requiredDocuments: ['Medical Certificate', 'Disability Certificate'],
    medicalCertificateRequired: true,
    fitnessCertificateOnReturn: true,
    prefixSuffixAllowed: false,
    applicableRegulations: ['REG-23'],
    isActive: true,
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },
];

// ============================================================================
// Leave Balances - For Demo Employees
// ============================================================================

export const LEAVE_BALANCES: LeaveBalance[] = [
  // Ravi Kumar (emp001) - EL
  {
    balanceId: 'bal001',
    userId: 'emp001',
    leaveTypeId: 'lt001',
    year: 2026,
    openingBalance: 45,
    credits: 30,
    totalAvailable: 75,
    availed: 12,
    pending: 0,
    balance: 63,
    spellsAvailed: 2,
    spellsPending: 0,
    spellsBalance: 10,
    lastUpdated: '2026-04-15T10:30:00Z',
  },
  // Ravi Kumar - HPL
  {
    balanceId: 'bal002',
    userId: 'emp001',
    leaveTypeId: 'lt002',
    year: 2026,
    openingBalance: 30,
    credits: 20,
    totalAvailable: 50,
    availed: 0,
    pending: 0,
    balance: 50,
    spellsAvailed: 0,
    spellsPending: 0,
    spellsBalance: 5,
    lastUpdated: '2026-04-15T10:30:00Z',
  },
  // Ravi Kumar - Casual Leave
  {
    balanceId: 'bal003',
    userId: 'emp001',
    leaveTypeId: 'lt005',
    year: 2026,
    openingBalance: 0,
    credits: 12,
    totalAvailable: 12,
    availed: 5,
    pending: 0,
    balance: 7,
    spellsAvailed: 3,
    spellsPending: 0,
    spellsBalance: 12,
    lastUpdated: '2026-04-15T10:30:00Z',
  },
  // Priya Sharma (emp002) - Similar balances
  {
    balanceId: 'bal004',
    userId: 'emp002',
    leaveTypeId: 'lt001',
    year: 2026,
    openingBalance: 35,
    credits: 30,
    totalAvailable: 65,
    availed: 8,
    pending: 0,
    balance: 57,
    spellsAvailed: 1,
    spellsPending: 0,
    spellsBalance: 10,
    lastUpdated: '2026-04-15T10:30:00Z',
  },
  {
    balanceId: 'bal005',
    userId: 'emp002',
    leaveTypeId: 'lt002',
    year: 2026,
    openingBalance: 25,
    credits: 20,
    totalAvailable: 45,
    availed: 0,
    pending: 0,
    balance: 45,
    spellsAvailed: 0,
    spellsPending: 0,
    spellsBalance: 5,
    lastUpdated: '2026-04-15T10:30:00Z',
  },
  {
    balanceId: 'bal006',
    userId: 'emp002',
    leaveTypeId: 'lt005',
    year: 2026,
    openingBalance: 0,
    credits: 12,
    totalAvailable: 12,
    availed: 3,
    pending: 0,
    balance: 9,
    spellsAvailed: 2,
    spellsPending: 0,
    spellsBalance: 12,
    lastUpdated: '2026-04-15T10:30:00Z',
  },
];

// ============================================================================
// Sample Regulations
// ============================================================================

export const REGULATIONS: Regulation[] = [
  {
    regulationId: 'reg001',
    regulationNumber: 'Regulation 1',
    title: 'Earned Leave',
    summary: 'Rules governing Earned Leave for APTRANSCO employees',
    fullText: 'Complete regulation text for Earned Leave...',
    category: 'Standard Leave',
    applicableLeaveTypes: ['lt001'],
    maxDaysAdmissible: 365,
    sanctioningNotes: 'Sanctioning authority as per delegation of powers',
    isActive: true,
    effectiveFrom: '2020-01-01',
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },
  {
    regulationId: 'reg017',
    regulationNumber: 'Regulation 17',
    title: 'Half Pay Leave and Commuted Leave',
    summary: 'Rules for HPL and conversion to Commuted Leave',
    fullText: 'Complete regulation text for Half Pay Leave...',
    category: 'Standard Leave',
    applicableLeaveTypes: ['lt002', 'lt003', 'lt004'],
    specialConditions: [
      'Medical certificate required for medical grounds',
      'Fitness certificate required upon return from medical leave',
    ],
    maxDaysAdmissible: 180,
    sanctioningNotes: 'Medical leave sanctioning follows special approval process',
    isActive: true,
    effectiveFrom: '2020-01-01',
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },
  {
    regulationId: 'reg018',
    regulationNumber: 'Regulation 18',
    title: 'Maternity Leave',
    summary: 'Rules for Maternity Leave (26 weeks provision)',
    fullText: 'Complete regulation text for Maternity Leave...',
    category: 'Special Leave',
    applicableLeaveTypes: ['lt007'],
    specialConditions: [
      'Applicable only to female employees',
      'Medical certificate with expected date of delivery required',
      'Pre-natal: up to 8 weeks before expected delivery',
      'Post-natal: remaining period after delivery',
    ],
    requiredDocuments: ['Medical Certificate', 'Expected Date of Delivery'],
    maxDaysAdmissible: 182,
    sanctioningNotes: 'Mandatory fitness certificate upon return',
    isActive: true,
    effectiveFrom: '2020-01-01',
    amendments: [
      {
        amendmentId: 'amd001',
        orderNumber: 'APTRANSCO/HR/2023/45',
        orderDate: '2023-06-15',
        summary: 'Extended from 12 weeks to 26 weeks',
        changes: 'Maternity leave period extended as per central government norms',
      },
    ],
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: '2023-06-15T10:30:00Z',
  },
];

// ============================================================================
// Delegation Matrix Sample
// ============================================================================

export const DELEGATION_MATRIX: DelegationMatrix[] = [
  {
    delegationId: 'del001',
    sanctioningAuthority: 'sa001',
    authorityName: 'Chief Engineer',
    authorityDesignation: 'Chief Engineer',
    applicableLeaveTypes: ['lt001', 'lt002', 'lt003', 'lt005'],
    applicableOffices: ['Eastern Zone', 'Central Zone'],
    maxDaysLimit: 60,
    delegationOrderNumber: 'APTRANSCO/ADMIN/DEL/2025/12',
    delegationOrderDate: '2025-01-15',
    isActive: true,
    effectiveFrom: '2025-02-01',
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },
  {
    delegationId: 'del002',
    sanctioningAuthority: 'sa002',
    authorityName: 'Personnel Officer',
    authorityDesignation: 'Personnel Officer',
    applicableLeaveTypes: ['lt007', 'lt008', 'lt009', 'lt010'],
    applicableOffices: ['Head Office'],
    delegationOrderNumber: 'APTRANSCO/HR/DEL/2025/08',
    delegationOrderDate: '2025-01-15',
    isActive: true,
    effectiveFrom: '2025-02-01',
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2026-04-15T10:30:00Z',
  },
];

// ============================================================================
// Demo Credentials
// ============================================================================

export const DEMO_CREDENTIALS = [
  { username: 'emp001', password: 'demo123', role: 'Employee' as const },
  { username: 'emp002', password: 'demo123', role: 'Employee' as const },
  { username: 'emp003', password: 'demo123', role: 'Employee' as const },
  { username: 'co001', password: 'demo123', role: 'ControllingOfficer' as const },
  { username: 'co002', password: 'demo123', role: 'ControllingOfficer' as const },
  { username: 'hr001', password: 'demo123', role: 'HR' as const },
  { username: 'hr002', password: 'demo123', role: 'HR' as const },
  { username: 'sa001', password: 'demo123', role: 'SanctionAuthority' as const },
  { username: 'sa002', password: 'demo123', role: 'SanctionAuthority' as const },
  { username: 'acc001', password: 'demo123', role: 'Accounts' as const },
  { username: 'admin001', password: 'demo123', role: 'Admin' as const },
];

// ============================================================================
// Utility Functions
// ============================================================================

export function getUserByUsername(username: string): User | undefined {
  return DEMO_USERS.find((user) => user.userId.toLowerCase() === username.toLowerCase());
}

export function getUserById(userId: string): User | undefined {
  return DEMO_USERS.find((user) => user.userId === userId);
}

export function getLeaveTypeById(leaveTypeId: string): LeaveType | undefined {
  return LEAVE_TYPES.find((lt) => lt.leaveTypeId === leaveTypeId);
}

export function getLeaveBalanceByUserAndType(
  userId: string,
  leaveTypeId: string
): LeaveBalance | undefined {
  return LEAVE_BALANCES.find(
    (lb) => lb.userId === userId && lb.leaveTypeId === leaveTypeId
  );
}

export function getEligibleLeaveTypes(user: User): LeaveType[] {
  return LEAVE_TYPES.filter((lt) => {
    if (!lt.isActive) return false;

    // Gender restriction
    if (lt.genderRestriction && lt.genderRestriction !== user.gender) {
      return false;
    }

    // Service years restriction
    if (lt.minServiceYears) {
      const joinDate = new Date(user.dateOfJoining);
      const now = new Date();
      const yearsOfService = (now.getTime() - joinDate.getTime()) / (1000 * 60 * 60 * 24 * 365);
      if (yearsOfService < lt.minServiceYears) {
        return false;
      }
    }

    return true;
  });
}

export function getLeaveBalance(userId: string, leaveTypeId: string): LeaveBalance | undefined {
  return LEAVE_BALANCES.find((lb) => lb.userId === userId && lb.leaveTypeId === leaveTypeId);
}

// ============================================================================
// Mock Leave Applications
// ============================================================================

const MOCK_APPLICATIONS: LeaveApplication[] = [
  {
    applicationId: 'APP-2026-001',
    userId: 'emp001',
    leaveTypeId: 'lt001',
    applicationDate: '2026-04-10',
    leaveFromDate: '2026-05-01',
    leaveFromSession: 'FN' as Session,
    leaveToDate: '2026-05-05',
    leaveToSession: 'AN' as Session,
    leaveDays: 5,
    totalDays: 5,
    reasonForLeave: 'Family vacation',
    leaveAddress: '123 Main Street, Hyderabad',
    contactNumber: '+91 9876543210',
    isMedicalLeave: false,
    status: 'PendingSanction',
    currentStage: 'SanctionAuthority',
    workflowHistory: [
      {
        historyId: 'WH-001-1',
        applicationId: 'APP-2026-001',
        actionDate: '2026-04-10T10:00:00Z',
        actionBy: 'emp001',
        actionByName: 'Ravi Kumar',
        action: 'Submitted',
        fromStatus: 'Draft',
        toStatus: 'Submitted',
        fromStage: 'Employee',
        toStage: 'ControllingOfficer',
        remarks: 'Application submitted for review',
        role: 'Employee',
      },
      {
        historyId: 'WH-001-2',
        applicationId: 'APP-2026-001',
        actionDate: '2026-04-11T14:30:00Z',
        actionBy: 'co001',
        actionByName: 'Ramesh Babu',
        action: 'Forwarded',
        fromStatus: 'Submitted',
        toStatus: 'Forwarded',
        fromStage: 'ControllingOfficer',
        toStage: 'HR',
        remarks: 'Application verified and forwarded',
        role: 'ControllingOfficer',
      },
      {
        historyId: 'WH-001-3',
        applicationId: 'APP-2026-001',
        actionDate: '2026-04-12T11:00:00Z',
        actionBy: 'hr001',
        actionByName: 'Suresh Reddy',
        action: 'ForwardedToSA',
        fromStatus: 'Forwarded',
        toStatus: 'PendingSanction',
        fromStage: 'HR',
        toStage: 'SanctionAuthority',
        remarks: 'Leave balance verified, forwarded to sanction authority',
        role: 'HR',
      },
    ],
    attachments: [],
    balanceAtApplication: 25,
    balanceAfterAvailing: 20,
    isEligible: true,
    applicableRegulations: ['REG-01'],
    createdAt: '2026-04-10T10:00:00Z',
    updatedAt: '2026-04-12T11:00:00Z',
  },
  {
    applicationId: 'APP-2026-002',
    userId: 'emp002',
    leaveTypeId: 'lt002',
    applicationDate: '2026-04-12',
    leaveFromDate: '2026-06-10',
    leaveFromSession: 'FN' as Session,
    leaveToDate: '2026-06-20',
    leaveToSession: 'AN' as Session,
    leaveDays: 11,
    totalDays: 11,
    reasonForLeave: 'Personal work',
    leaveAddress: '456 Park Avenue, Vijayawada',
    contactNumber: '+91 9876543211',
    isMedicalLeave: false,
    status: 'PendingSanction',
    currentStage: 'SanctionAuthority',
    workflowHistory: [
      {
        historyId: 'WH-002-1',
        applicationId: 'APP-2026-002',
        actionDate: '2026-04-12T09:00:00Z',
        actionBy: 'emp002',
        actionByName: 'Priya Sharma',
        action: 'Submitted',
        fromStatus: 'Draft',
        toStatus: 'Submitted',
        fromStage: 'Employee',
        toStage: 'ControllingOfficer',
        remarks: 'Application submitted',
        role: 'Employee',
      },
      {
        historyId: 'WH-002-2',
        applicationId: 'APP-2026-002',
        actionDate: '2026-04-13T10:00:00Z',
        actionBy: 'co001',
        actionByName: 'Ramesh Babu',
        action: 'Forwarded',
        fromStatus: 'Submitted',
        toStatus: 'Forwarded',
        fromStage: 'ControllingOfficer',
        toStage: 'HR',
        remarks: 'Forwarded after review',
        role: 'ControllingOfficer',
      },
      {
        historyId: 'WH-002-3',
        applicationId: 'APP-2026-002',
        actionDate: '2026-04-14T15:00:00Z',
        actionBy: 'hr002',
        actionByName: 'Anitha Kumari',
        action: 'ForwardedToSA',
        fromStatus: 'Forwarded',
        toStatus: 'PendingSanction',
        fromStage: 'HR',
        toStage: 'SanctionAuthority',
        remarks: 'Balance verified, sent to sanction authority',
        role: 'HR',
      },
    ],
    attachments: [],
    balanceAtApplication: 30,
    balanceAfterAvailing: 19,
    isEligible: true,
    applicableRegulations: ['REG-17'],
    createdAt: '2026-04-12T09:00:00Z',
    updatedAt: '2026-04-14T15:00:00Z',
  },
  {
    applicationId: 'APP-2026-003',
    userId: 'emp003',
    leaveTypeId: 'lt001',
    applicationDate: '2026-04-05',
    leaveFromDate: '2026-05-15',
    leaveFromSession: 'FN' as Session,
    leaveToDate: '2026-05-17',
    leaveToSession: 'AN' as Session,
    leaveDays: 3,
    totalDays: 3,
    reasonForLeave: 'Medical checkup',
    leaveAddress: '789 Station Road, Guntur',
    contactNumber: '+91 9876543212',
    isMedicalLeave: false,
    status: 'Sanctioned',
    currentStage: 'Accounts',
    workflowHistory: [
      {
        historyId: 'WH-003-1',
        applicationId: 'APP-2026-003',
        actionDate: '2026-04-05T11:00:00Z',
        actionBy: 'emp003',
        actionByName: 'Anil Reddy',
        action: 'Submitted',
        fromStatus: 'Draft',
        toStatus: 'Submitted',
        fromStage: 'Employee',
        toStage: 'ControllingOfficer',
        remarks: 'Application submitted',
        role: 'Employee',
      },
      {
        historyId: 'WH-003-2',
        applicationId: 'APP-2026-003',
        actionDate: '2026-04-06T14:00:00Z',
        actionBy: 'co002',
        actionByName: 'Lakshmi Devi',
        action: 'Forwarded',
        fromStatus: 'Submitted',
        toStatus: 'Forwarded',
        fromStage: 'ControllingOfficer',
        toStage: 'HR',
        remarks: 'Reviewed and forwarded',
        role: 'ControllingOfficer',
      },
      {
        historyId: 'WH-003-3',
        applicationId: 'APP-2026-003',
        actionDate: '2026-04-08T10:00:00Z',
        actionBy: 'hr001',
        actionByName: 'Suresh Reddy',
        action: 'ForwardedToSA',
        fromStatus: 'Forwarded',
        toStatus: 'PendingSanction',
        fromStage: 'HR',
        toStage: 'SanctionAuthority',
        remarks: 'Verified and sent for sanction',
        role: 'HR',
      },
      {
        historyId: 'WH-003-4',
        applicationId: 'APP-2026-003',
        actionDate: '2026-04-09T16:00:00Z',
        actionBy: 'sa002',
        actionByName: 'P. Venkateswara Rao',
        action: 'Sanctioned',
        fromStatus: 'PendingSanction',
        toStatus: 'Sanctioned',
        fromStage: 'SanctionAuthority',
        toStage: 'Accounts',
        remarks: 'Leave application sanctioned',
        role: 'SanctionAuthority',
      },
    ],
    attachments: [],
    balanceAtApplication: 22,
    balanceAfterAvailing: 19,
    isEligible: true,
    applicableRegulations: ['REG-01'],
    sapPostingStatus: 'Pending',
    createdAt: '2026-04-05T11:00:00Z',
    updatedAt: '2026-04-09T16:00:00Z',
  },
  {
    applicationId: 'APP-2026-004',
    userId: 'emp001',
    leaveTypeId: 'lt003',
    applicationDate: '2026-04-14',
    leaveFromDate: '2026-05-20',
    leaveFromSession: 'FN' as Session,
    leaveToDate: '2026-05-22',
    leaveToSession: 'AN' as Session,
    leaveDays: 3,
    totalDays: 3,
    reasonForLeave: 'Family function',
    leaveAddress: '321 Temple Road, Guntur',
    contactNumber: '+91 9876543213',
    isMedicalLeave: false,
    status: 'Forwarded',
    currentStage: 'HR',
    workflowHistory: [
      {
        historyId: 'WH-004-1',
        applicationId: 'APP-2026-004',
        actionDate: '2026-04-14T10:00:00Z',
        actionBy: 'emp001',
        actionByName: 'Ravi Kumar',
        action: 'Submitted',
        fromStatus: 'Draft',
        toStatus: 'Submitted',
        fromStage: 'Employee',
        toStage: 'ControllingOfficer',
        remarks: 'Application submitted',
        role: 'Employee',
      },
      {
        historyId: 'WH-004-2',
        applicationId: 'APP-2026-004',
        actionDate: '2026-04-15T11:30:00Z',
        actionBy: 'co001',
        actionByName: 'Ramesh Babu',
        action: 'Forwarded',
        fromStatus: 'Submitted',
        toStatus: 'Forwarded',
        fromStage: 'ControllingOfficer',
        toStage: 'HR',
        remarks: 'Verified and forwarded to HR',
        role: 'ControllingOfficer',
      },
    ],
    attachments: [],
    balanceAtApplication: 18,
    balanceAfterAvailing: 15,
    isEligible: true,
    applicableRegulations: ['REG-01'],
    createdAt: '2026-04-14T10:00:00Z',
    updatedAt: '2026-04-15T11:30:00Z',
  },
  {
    applicationId: 'APP-2026-005',
    userId: 'emp002',
    leaveTypeId: 'lt001',
    applicationDate: '2026-04-13',
    leaveFromDate: '2026-06-01',
    leaveFromSession: 'FN' as Session,
    leaveToDate: '2026-06-10',
    leaveToSession: 'AN' as Session,
    leaveDays: 10,
    totalDays: 10,
    reasonForLeave: 'Personal travel',
    leaveAddress: '789 Beach Road, Visakhapatnam',
    contactNumber: '+91 9876543214',
    isMedicalLeave: false,
    status: 'Forwarded',
    currentStage: 'HR',
    workflowHistory: [
      {
        historyId: 'WH-005-1',
        applicationId: 'APP-2026-005',
        actionDate: '2026-04-13T14:00:00Z',
        actionBy: 'emp002',
        actionByName: 'Priya Sharma',
        action: 'Submitted',
        fromStatus: 'Draft',
        toStatus: 'Submitted',
        fromStage: 'Employee',
        toStage: 'ControllingOfficer',
        remarks: 'Leave application submitted',
        role: 'Employee',
      },
      {
        historyId: 'WH-005-2',
        applicationId: 'APP-2026-005',
        actionDate: '2026-04-14T16:00:00Z',
        actionBy: 'co001',
        actionByName: 'Ramesh Babu',
        action: 'Forwarded',
        fromStatus: 'Submitted',
        toStatus: 'Forwarded',
        fromStage: 'ControllingOfficer',
        toStage: 'HR',
        remarks: 'Application checked and forwarded',
        role: 'ControllingOfficer',
      },
    ],
    attachments: [],
    balanceAtApplication: 20,
    balanceAfterAvailing: 10,
    isEligible: true,
    applicableRegulations: ['REG-01'],
    createdAt: '2026-04-13T14:00:00Z',
    updatedAt: '2026-04-14T16:00:00Z',
  },
  {
    applicationId: 'APP-2026-006',
    userId: 'emp003',
    leaveTypeId: 'lt002',
    applicationDate: '2026-04-15',
    leaveFromDate: '2026-06-15',
    leaveFromSession: 'FN' as Session,
    leaveToDate: '2026-06-25',
    leaveToSession: 'AN' as Session,
    leaveDays: 11,
    totalDays: 11,
    reasonForLeave: 'Health recovery',
    leaveAddress: '456 Lake View, Hyderabad',
    contactNumber: '+91 9876543215',
    isMedicalLeave: true,
    status: 'Submitted',
    currentStage: 'ControllingOfficer',
    workflowHistory: [
      {
        historyId: 'WH-006-1',
        applicationId: 'APP-2026-006',
        actionDate: '2026-04-15T09:00:00Z',
        actionBy: 'emp003',
        actionByName: 'Anil Reddy',
        action: 'Submitted',
        fromStatus: 'Draft',
        toStatus: 'Submitted',
        fromStage: 'Employee',
        toStage: 'ControllingOfficer',
        remarks: 'Application submitted for review',
        role: 'Employee',
      },
    ],
    attachments: [],
    balanceAtApplication: 28,
    balanceAfterAvailing: 17,
    isEligible: true,
    applicableRegulations: ['REG-17'],
    createdAt: '2026-04-15T09:00:00Z',
    updatedAt: '2026-04-15T09:00:00Z',
  },
];

export function getApplicationsByStatus(status: string): LeaveApplication[] {
  return MOCK_APPLICATIONS.filter((app) => app.status === status);
}

export function getApplicationById(applicationId: string): LeaveApplication | undefined {
  return MOCK_APPLICATIONS.find((app) => app.applicationId === applicationId);
}

export function updateApplicationStatus(applicationId: string, newStatus: any): void {
  const app = MOCK_APPLICATIONS.find((a) => a.applicationId === applicationId);
  if (app) {
    app.status = newStatus;
  }
}

export function addWorkflowHistory(applicationId: string, historyItem: any): void {
  const app = MOCK_APPLICATIONS.find((a) => a.applicationId === applicationId);
  if (app) {
    app.workflowHistory.push(historyItem);
  }
}
